<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    //
    protected $fillable = ['title','body','slug','user_id','category_id'];

    protected $with = ['answers'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($question){

            $question->slug = str_slug($question->title);

        });

        static::updating(function ($question){

            $question->slug = str_slug($question->title);

        });
    }

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
    public function user(){
        return $this->belongsTo(User::class);
    }

    public function answers(){
        return $this->hasMany(Answer::class);
    }
    public function category(){
        return $this->belongsTo(Category::class);
    }
    public function getPathAttribute(){
        return "/question/$this->slug";
    }
}
